# fly.toml app configuration file generated for interview-transcriber on 2025-06-15T11:01:03-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'interview-transcriber'
primary_region = 'bos'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  max_machines_count = 1
  processes = ['app']

[env]
  JOBS_DIR = '/data/jobs'
  OUTPUT_DIR = '/data/output'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[mounts]
  source = "transcribervol"
  destination = "/data"
